### PR TITLE
Fix PlistQueue, add more tests

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
@stevelinton the reason that the test stops at 32 right now is that the tested code actually is broken, which will show for N>=64. I merely picked 32 because the old test had 32 -- and made sure that the value is trivial to increase, once @markuspf (or anybody else) fixes the underlying broken code.

And of course there should be more tests, with additional types of objects being inserted, and in more complicated ways etc., but that would be for a future PR. Point is: already this test (once one makes the trivial change to replace 32 by 64) reveals a bug, which is why I did not bother to write more tests -- let's fix the bug first :)

**Comment by fingolfin** [comment]
Also note that right now, this package does not make any attempts to support HPC-GAP, and we don't even run tests there. Setting up HPC-GAP checks on Travis would be easy, but then somebody needs to devise a testing framework for concurrent access in HPC-GAP. Unfortunately, no such testing framework currently exists, which is IMHO one of the major pain points with writing HPC-GAP code (and indeed, also perhaps part of the reason HPC-GAP development is basically stalled, and quite likely to be regressed, too, as I think nobody makes any serious and systematic attempts to test what does and what doesn't work on it...

**Comment by stevelinton** [comment]
Fair enough. Happy for this to merge as is.

**Comment by markuspf** [comment]
I think I took everything from this PR on board for #59.

**Pull request closed without merging**
